[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quati"
version = "1.5.0"
description = "A professional-grade toolkit for seamless automation and workflow optimization"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

authors = [
  { name = "lucasoal" }
]

keywords = [
  "quick", "actions", "toolkit", "functions"
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.10",
  "Topic :: Software Development :: Libraries"
]

dependencies = [
  "google-cloud-bigquery",
  "google-cloud-bigquery-storage",
  "gspread",
  "oauthlib",
  "pandas",
  "pandas-gbq",
  "requests",
  "selenium",
  "tqdm"
]

[project.urls]
Homepage = "https://pypi.org/project/quati"
Documentation = "https://github.com/quati-dev/quati/blob/main/doc/DOCUMENTATION.md"
Repository = 'https://github.com/quati-dev/quati'

[tool.setuptools.packages.find]
where = ["."]
include = ["quati*"]

[tool.setuptools]
include-package-data = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = ["tests"]
